### ISSUE TITLE
is this work well?

### ISSUE THREAD

**Issue by white-ubuntu** [mskec/react-native-mp-android-chart-example#1]
hi,is this work well?i have some problems.

**Comment by mskec** [comment]
Hi @white-ubuntu,

This example app is working, but it is not correctly connected with [react-native-mp-android-chart library](https://github.com/mskec/react-native-mp-android-chart). 

It is still work in progress and I will correctly connect it in the following weeks.

**Comment by white-ubuntu** [comment]
how is it going on?

**Comment by mskec** [comment]
I just published to npm. 
Checkout library repo https://github.com/mskec/react-native-mp-android-chart and let me know if you have any problems.
