### ISSUE TITLE
only border without data

### ISSUE THREAD

**Issue by zengyanzi** [mskec/react-native-mp-android-chart-example#3]
I tried this code and want to test the example, but only the border without data as below
![image](https://cloud.githubusercontent.com/assets/21092607/19463751/2bac7e6a-9553-11e6-8970-7f05086c04a8.png)

**Comment by mskec** [comment]
Did you try this in your app or did you run example app?

**Comment by zengyanzi** [comment]
I try this in my app as below 

import React from 'react';

import {
   Image,
  View,
  Text,
  StyleSheet,
  ViewPagerAndroid,
  BackAndroid,
  navigator,
  Animated,
} from 'react-native';
import {BarChart} from 'react-native-mp-android-chart';

BackAndroid.addEventListener('hardwareBackPress', function() {
  if(_navigator == null){
    return false;
  }
  if(_navigator.getCurrentRoutes().length === 1){
    return false;
  }
  _navigator.pop();
  return true;
});

var _navigator ;

class MyrecordView extends React.Component {

  constructor() {
    super();

```
this.state = {
  data: {
    datasets: [{
      yValues: [100, 105, 102, 110],
      label: 'Data set 1',
      config: {
        color: 'teal'
      }
    }, {
      yValues: [110, 100, 105, 108],
      label: 'Data set 2',
      config: {
        color: 'orange'
      }
    }],
    xValues: ['Q1', 'Q2', 'Q3', 'Q4']
  }
};
```

  }

  render() {
    return (
      <View>
        <BarChart
          style={styles.chart}
          data={this.state.data}
          animation={{durationX: 2000}}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  chart: {
    height: 300,
    width: 300
  }
});
export default MyrecordView;

Thank you very much !

**Comment by mskec** [comment]
Check [BarChartScreen example](https://github.com/mskec/react-native-mp-android-chart-example/blob/master/app/BarChartScreen.js) to see how it works.
