### ISSUE TITLE
xAxis labels are not updating

### ISSUE THREAD

**Issue by bharbi** [mskec/react-native-mp-android-chart-example#6]
xAxis labels are not updating dynamically. Iam changing Xaxis labels 10 to 20. initially it was taking 10 labels, later setting to 20 labels , But Xaxis labels are not updating

**Comment by mskec** [comment]
Hi @bharbi,
This is only example application repository. The library repository is here https://github.com/mskec/react-native-mp-android-chart and it's not maintained anymore. 
You should check out this lib https://github.com/wuxudong/react-native-charts-wrapper
